stages:
  - test
  - build
  - docker
  - update-manifests

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

test:
  stage: test
  tags:
    - docker
  script:
    - echo "Testing..."
    - cd app
    - chmod +x mvnw
    - ./mvnw test

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Building..."
    - cd app
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - app/target/*.jar
    expire_in: 1 hour

docker:
  stage: docker
  tags:
    - docker
  script:
    - echo "Building Docker image..."
    - docker build -t saeedgebaly/employee-management:$CI_COMMIT_SHORT_SHA -t saeedgebaly/employee-management:latest app
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push saeedgebaly/employee-management:$CI_COMMIT_SHORT_SHA
    - docker push saeedgebaly/employee-management:latest

update-manifests:
  stage: update-manifests
  tags:
    - docker
  script:
    - echo "Updating manifests..."
    - 'sed -i "s|image: saeedgebaly/employee-management:.*|image: saeedgebaly/employee-management:${CI_COMMIT_SHORT_SHA}|g" manifests/app/app-deployment.yaml'
    - git config user.email "gitlab-ci@gitlab.com"
    - git config user.name "GitLab CI"

    - git remote set-url origin https://oauth2:${GITLAB_TOKEN}@gitlab.com/saeedgebaly7/devops-employee-management-system.git
    - git fetch origin gitops
    - git checkout -B gitops origin/gitops
    - 'sed -i "s|image: saeedgebaly/employee-management:.*|image: saeedgebaly/employee-management:${CI_COMMIT_SHORT_SHA}|g" manifests/app/app-deployment.yaml'

    - git add manifests/app/app-deployment.yaml
    - git diff --cached --quiet || git commit -m "Update image tag ${CI_COMMIT_SHORT_SHA} [skip ci]"
    - git push origin HEAD:gitops
  only:
    - develop
