stages:
  - test
  - build
  - image-build
  - security-scan
  - docker-push
  - update-manifests

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

test:
  stage: test
  tags:
    - docker
  script:
    - echo "Testing..."
    - cd app
    - chmod +x mvnw
    - ./mvnw test

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Building..."
    - cd app
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - app/target/*.jar
    expire_in: 1 hour

image-build:
  stage: image-build
  dependencies:
    - build
  tags:
    - docker

  script:
    - docker build -t employee-management:${CI_COMMIT_SHORT_SHA} app

security-scan:
  stage: security-scan
  dependencies:
    - image-build
  tags:
    - docker

  script:
    - |
      docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /home/gitlab-runner/.cache/trivy/trivy:/root/.cache/trivy \
        aquasec/trivy:0.71.2 image \
        --scanners vuln \
        --skip-db-update \
        --skip-java-db-update \
        --skip-version-check \
        --severity CRITICAL \
        --exit-code 1 \
        employee-management:${CI_COMMIT_SHORT_SHA}

  artifacts:
    paths:
      - trivy-report.txt
    expire_in: 7 days

docker-push:
  stage: docker-push
  dependencies:
    - security-scan
  tags:
    - docker

  script:
    - docker tag employee-management:${CI_COMMIT_SHORT_SHA} saeedgebaly/employee-management:${CI_COMMIT_SHORT_SHA}
    - docker tag employee-management:${CI_COMMIT_SHORT_SHA} saeedgebaly/employee-management:latest

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - docker push saeedgebaly/employee-management:${CI_COMMIT_SHORT_SHA}
    - docker push saeedgebaly/employee-management:latest

update-manifests:
  stage: update-manifests
  tags:
    - docker
  script:
    - echo "Updating manifests..."
    - git config user.email "gitlab-ci@gitlab.com"
    - git config user.name "GitLab CI"

    - git remote set-url origin https://oauth2:${GITLAB_TOKEN}@gitlab.com/saeedgebaly7/devops-employee-management-system.git
    - git fetch origin gitops
    - git checkout -B gitops origin/gitops
    - 'sed -i "s|image: saeedgebaly/employee-management:.*|image: saeedgebaly/employee-management:${CI_COMMIT_SHORT_SHA}|g" manifests/app/app-deployment.yaml'

    - git add manifests/app/app-deployment.yaml
    - git diff --cached --quiet || git commit -m "Update image tag ${CI_COMMIT_SHORT_SHA} [skip ci]"
    - git push origin HEAD:gitops
  only:
    - develop
