apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: employee-management
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: employee-management
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
