apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.com/saeedgebaly7/devops-employee-management-system.git
  username: oauth2
  password: glpat-7hx4QJiPLhqX2bJdO6RTRWM6MQpvOjEKdTpub3U0MQ8.01.171p3iy95
type: Opaque
